config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]

  get 'sessions/destroy'

  resources :posts do
    resources :votes
    get '/up', to: "votes#up"
    get '/down', to: "votes#down"
  end

  resources :users do
    resources :posts
  end

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :votes
  has_many :comments

  validates :title, :text, presence: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def summ_votes_to_post
    summ = votes.where(vote_type: 'up').count - votes.where(vote_type: 'down').count

    if summ < 0
      summ = 0
    else
      summ
    end
  end

  def vote_up(user)
    down = votes.find_by(user_id: user.id, vote_type: 'down')
    down.destroy if down.present?

    votes.create({ user_id: user.id }.merge(vote_type: 'up'))
  end

  def vote_down(user)
    up = votes.find_by(user_id: user.id, vote_type: 'up')
    up.destroy if up.present?

    votes.create({ user_id: user.id }.merge(vote_type: 'down'))
  end

  def from_vote_up?(user)
    votes.where({user_id: user.id, vote_type: 'up'}).present?
  end

  def from_vote_down?(user)
    votes.where({user_id: user.id, vote_type: 'down'}).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :votes
  has_many :comments

  validates :name, presence: true, uniqueness: true
  validates :password, :length => {:in => 4..15}
  validates :name, :length => {:maximum => 12}

  has_secure_password
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/vote_down.rb
class VoteDown < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/vote_table.rb
class VoteTable < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user

  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def input_user_to_session
    session[:user_id] = @user.id
  end

  def authenticate_user
    redirect_to new_sessions_path, alert: "Пожалуйста, пройдите аутентификацию" unless current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def authorize_admin
    if current_user.name != 'admin'
      redirect_to new_sessions_path, alert: 'У Вас нет прав на это действие, пожалуйста пройдите авторизацию'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user, only: [ :index, :show ]

  def index
    @posts = Post.all
    @link_number = 0
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params.merge(:user_id => current_user.id))

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user

  def new
    current_user
  end

  def create
     @user = User.find_by(name: params[:name])

    if @user && @user.authenticate(params[:password])
      input_user_to_session

      redirect_to root_path
    else
      redirect_to new_sessions_path, alert: "Пароль или логин неверен"
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [ :new, :create ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    set_user
  end

  def update
    set_user
  end

  def edit
    set_user
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        input_user_to_session
        format.html { redirect_to @user, notice: 'Пользователь был успешно создан.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_user

    if current_user.name == 'admin'
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'Пользователь был успешно удален.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def up
    find_post

    @post.vote_up(@current_user)

    redirect_to root_path
  end

  def down
    find_post

    @post.vote_down(@current_user)

    redirect_to root_path
  end

  def destroy
    find_post

    @vote = @post.votes.find_by(:user_id => @current_user.id, vote_type: ['up', 'down'])

    @vote.destroy

    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def vote_params
    params.permit(:id, :post_id, :user_id, :vote_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="all-content">
      <div id="nav">
        <span id="first-link"><%= link_to("MY SUBREDDITS", "url") %></span>
        <span><%= link_to("HOME", root_path) %></span>
        -
        <span><%= link_to("POPULAR", "url") %></span>
        -
        <span><%= link_to("ALL", "url") %></span>
        -
        <span><%= link_to("RANDOM", "url") %></span>
        |   |
        <span><%= link_to("ASKREDDIT", "url") %></span>
        -
        <span><%= link_to("WORLDNEWS", "url") %></span>
        -
        <span><%= link_to("FUNNY", "url") %></span>
        -
        <span><%= link_to("VIDEOS", "url") %></span>
        -
        <span><%= link_to("PICS", "url") %></span>
        -
        <span><%= link_to("NEWS", "url") %></span>
        -
        <span><%= link_to("GIFS", "url") %></span>
        -
        <span><%= link_to("TODAYILERNES", "url") %></span>
        -
        <span><%= link_to("AWW", "url") %></span>
        -
        <span><%= link_to("GAMING", "url") %></span>
        -
        <span><%= link_to("MOVIES", "url") %></span>
        -
        <span><%= link_to("SHOWERTHOUGHTS", "url") %></span>
        -
        <span><%= link_to("JOKES", "url") %></span>
        -
        <span><%= link_to("FUTUROLOGY", "url") %></span>
        -
        <span><%= link_to("SCIENCE", "url") %></span>
        -
        <span><%= link_to("TELEVISION", "url") %></span>
        -
        <span><%= link_to("TWOXCHROMOSOMES", "url") %></span>
        -
        <span><%= link_to("OLDSCHOOLCOOL", "url") %></span>
        -
        <span><%= link_to("DATAISBEAUTIFUL", "url") %></span>
        -
        <span><%= link_to("NOTTHEONION", "url") %></span>
        -
        <span><%= link_to("LIFEPROTIPS", "url") %></span>
        -
        <span><%= link_to("IAMA", "url") %></span>
      </div>
      <div id="upper">
        <%= link_to image_tag("https://b.thumbs.redditmedia.com/-KIq1WArgXPnB02N493dZuaRlH_Q_ypFC7S5PQ3I9wE.png", size: "120x40", id: "img"),root_path %>

        <div id="navi-top">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#home" role="tab">hot</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#profile" role="tab">new</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#messages" role="tab">rising</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#settings" role="tab">controversial</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#settings" role="tab">top</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#settings" role="tab">gided</a>
            </li>
          </ul>
        </div>

        <div class="input">
          <% if current_user %>
            <span><%= current_user.name %></span>
            <span>|</span>
            <span><%= link_to('logout', sessions_destroy_path) %></span>
          <% else %>
            <span><%= link_to('log in', new_sessions_path) %></span>
          <% end %>
        </div>
      </div>

      <%= yield %>

    </div>
  </body>
</html>

app/views/posts/_post_form.html.erb
<div class="save-form" >
  <%= form_for @post do |f| %>
    <div class="table-row" >
      <span class="table-cell name"><%= f.label 'url' %></span>
      <span class="table-cell"><%= f.text_field :title, size: "30" %></span>
    </div>

    <div class="table-row" >
      <span class="table-cell name"><%= f.label :image %></span>
      <span class="table-cell"><%= f.file_field :image %></span>
    </div>

    <div class="table-row" >
      <span class="table-cell name"><%= f.label 'title' %></span>
      <span class="table-cell"><%= f.text_area :text, size: "80x20" %></span>
    </div>

    <div class="table-row">
      <span class="table-cell"></span>
      <span class="table-cell">
        <%= f.submit 'submit', class: 'btn btn-primary' %>
        <%= link_to("Back", :back, class: 'btn btn-outline-secondary') %>
      </span>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="post-index">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-id"><%= @link_number += 1 %></div>

      <div class="vote">
        <% if current_user %>
          <div class="vote-attribute">
            <%= link_to_if(post.from_vote_up?(current_user), image_tag("up_press.png"), post_vote_path(post, :id), method: :delete) do
              link_to(image_tag("up.png"), post_up_path(post))
            end %>
          </div>
        <% else %>
            <div class="vote-attribute"><%= image_tag "up.png" %></div>
        <% end %>

        <div class="vote-attribute"><%= post.summ_votes_to_post %></div>

        <% if current_user %>
          <div class="vote-attribute">
            <%= link_to_if(post.from_vote_down?(current_user), image_tag("down_press.png"), post_vote_path(post, :id), method: :delete) do
              link_to(image_tag("down.png"), post_down_path(post))
            end %>
          </div>
        <% else %>
            <div class="vote-attribute"><%= image_tag "down.png" %></div>
        <% end %>
      </div>

      <div class="post-image">
        <% if post.image.present? %>
          <%= link_to((image_tag post.image.url, width: "70"), post.title) %>
        <% else %>
          <%= link_to((image_tag '1111.jpeg', width: "70"), post.title) %>
        <% end %>
      </div>
      <div class="post-body">
        <div id="rew">
          <h4><%= link_to post.text, post.title %></h4>
        </div>
        <div class="icon"></div>
        <div class="icon2">
          <div class="post-title">
            <span><%= post.created_at.strftime("submitted %F by") %></span>
            <span><%= User.find_by(:id => post.user_id).name %></span>
            <span> to r/funny</span>
          </div>
          <div class="post-title" id="post-title">
            <span><%= link_to("comment", "url") %></span>
            <span><%= link_to("share", "url") %></span>
            <span><%= link_to("save", "url") %></span>
            <span><%= link_to("hide", "url") %></span>
            <span><%= link_to("report", "url") %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="sidebar">
  <div class="search">
    <%= form_tag("/search", :method => "get") do %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
  <div class="sidebar1"></div>
  <div class="new-link"><%= link_to 'Submit a new link', new_post_path %></div>
  <div class="new-link"><%= link_to 'Submit a new text post', '#' %></div>
  <div class="sidebar2"></div>
</div>

app/views/posts/new.html.erb
<div id="new-link">
  <h1>New link</h1>

  <%= render 'post_form' %>
</div>

app/views/posts/show.html.erb
<div class="post-show">
    <h3><%= @post.title %></h3>
    <%= image_tag @post.image.url, size: "480x260" %>
    <p><%= @post.text %></p>
    <div>
      <%= link_to("Back", :back, class: 'btn btn-outline-secondary') %>
      <%= link_to("Delete link", post_path(@post), method: :delete, data: { confirm: 'Вы уверены?'}, class: 'btn btn-outline-secondary') %>
    </div>
</div>

app/views/users/_reg_form.html.erb
<%= form_for(@user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Введите сведения о пользователе</legend>

    <div class="table-row">
      <span class="table-cell name"><%= f.label 'Имя' %></span>
      <span class="table-cell"><%= f.text_field :name %></span>
    </div>

    <div class="table-row" >
      <span class="table-cell name"><%= f.label :email %></span>
      <span class="table-cell"><%= f.email_field :email %></span>
    </div>

    <div class="table-row">
      <span class="table-cell name"><%= f.label 'Пароль' %></span>
      <span class="table-cell"><%= f.password_field :password %></span>
    </div>

    <div class="table-row">
      <span class="table-cell name"><%= f.label 'Подтвердить пароль' %></span>
      <span class="table-cell"><%= f.password_field :password_confirmation %></span>
    </div>

    <div class="table-row">
      <span class="table-cell name"></span>
      <span class="table-cell"><%= f.submit 'Создать пользователя' %></span>
    </div>
  </fieldset>
<% end %>

app/views/users/new.html.erb
<br>
<h1>Регистрация пользователя</h1>

<%= render 'reg_form', user: @user %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', :back %>